name: 'Run Android Tests'
description: 'Runs Android Instrumentation tests on Android Emulator'
inputs:
  api-level:
    description: 'Android Emulator image version'
    required: true
    default: '29'
  build-command:
    description: 'Command to execute for building Android Tests'
    required: true
    default: 'assembleDebugAndroidTest'
  test-command:
    description: 'Command to execute for running Android Tests'
    required: true
    default: 'connectedDebugAndroidTest'
runs:
  using: "composite"
  steps:
    - name: Set permissions
      run: chmod +x ./gradlew
      shell: bash

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - uses: burrunan/gradle-cache-action@v1
      name: build-android-tests
      with:
        debug: false
        job-id: android-test
        read-only: ${{ github.ref != 'refs/heads/main' }}
        gradle-dependencies-cache-key: |
          gradle/libs.versions.toml
          build-logic/**/Constants.kt
        arguments: ${{ inputs.build-command }}

    - name: AVD Cache
      uses: actions/cache@v2
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.api-level }}

    - name: Create AVD and generate snapshot for caching
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api-level }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew ${{ inputs.test-command }}