name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  TERM: dumb

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: lint
        with:
          debug: false
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: lintDebug spotlessCheck apiCheck
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: build
        with:
          debug: false
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: assembleDebug --scan
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: unit-tests
        with:
          debug: false
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: testDebugUnitTest --scan
  ui-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run instrumentation tests
        uses: ./.github/actions/android-test
        with:
          api-level: 29
  publish-snapshots:
    runs-on: ubuntu-latest
    needs: [ unit-tests, build, lint, ui-tests ]
    if: ${{ github.ref == 'refs/heads/main' }}
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: publish-snapshots
        env:
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          debug: false
          job-id: publish-snapshots
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: publishReleasePublicationToSonatypeRepository -Psnapshot --rerun-tasks
  publish-release:
    runs-on: ubuntu-latest
    needs: [ unit-tests, build, lint, ui-tests ]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: publish-snapshots
        env:
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          debug: false
          job-id: publish-snapshots
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: help -Psnapshot --rerun-tasks